name: Keep Streamlit Apps Awake
on:
  schedule:
    - cron: "0 */2 * * *" # Runs every 2 hours
  workflow_dispatch:      # Allows you to trigger it manually via GitHub if needed
jobs:
  wake-apps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install playwright
          playwright install chromium
      - name: Run script
        run: python keep_awake.py
